version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/examples/*"
    schedule:
      interval: "daily"
    groups:
      cargo-all:
        patterns:
          - "*"
        group-by: dependency-name
