version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/examples/*"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
    groups:
      cargo-all:
        patterns:
          - "*"
        group-by: dependency-name
