
[package]
name = "cli-xtask"
version = "0.1.0-alpha.0"
edition = "2021"
rust-version = "1.59.0"
description = "xtask workflow collection for cli application"
readme = "README.md"
repository = "https://github.com/gifnksm/cli-xtask"
license = "MIT OR Apache-2.0"
keywords = []
categories = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
cargo-readme = "3.2.0"

[build-dependencies]

[profile.dev]

[profile.release]

[badges]
maintenance = { status = "actively-developed" }
