pre-release-replacements = [
  {file = "CHANGELOG.md", search = "Unreleased", replace = "{{version}}"},
  {file = "CHANGELOG.md", search = "/commits/HEAD", replace = "/commits/{{tag_name}}", min = 0, max = 1},
  {file = "CHANGELOG.md", search = "\\.\\.\\.HEAD", replace = "...{{tag_name}}", min = 0, max = 1},
  {file = "CHANGELOG.md", search = "ReleaseDate", replace = "{{date}}"},
  {file = "CHANGELOG.md", search = "<!-- next-header -->", replace = "<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly = 1},
  {file = "CHANGELOG.md", search = "<!-- next-url -->", replace = "<!-- next-url -->\n[Unreleased]: https://github.com/gifnksm/cli-xtask/compare/{{tag_name}}...HEAD", exactly = 1},
  {file = "README.md", search = "cli-xtask = \".*\"$", replace = "cli-xtask = \"{{version}}\"", exactly = 1},
  {file = "src/lib.rs", search = "^//! cli-xtask = \".*\"$", replace = "//! cli-xtask = \"{{version}}\"", exactly = 1},
  {file = "src/lib.rs", search = "^#!\\[doc\\(html_root_url = \"https://docs.rs/cli-xtask/.*\"\\)\\]$", replace = "#![doc(html_root_url = \"https://docs.rs/cli-xtask/{{version}}\")]", exactly = 1},
]
pre-release-hook = ["cargo", "xtask", "pre-release"]
dev-version = true
